;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities.Attack.SwordCombo",DevComment="")
+GameplayTagList=(Tag="Abilities.FrozenSimulacrum",DevComment="")
+GameplayTagList=(Tag="Abilities.GlacialCharge",DevComment="")
+GameplayTagList=(Tag="Abilities.Hoarfrost",DevComment="")
+GameplayTagList=(Tag="Cooldown.FrozenSimulacrum",DevComment="")
+GameplayTagList=(Tag="Cooldown.GlacialCharge",DevComment="")
+GameplayTagList=(Tag="Cooldown.Hoarfrost",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Combo.End",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Combo.Input",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Combo.Start",DevComment="")
+GameplayTagList=(Tag="Event.Attack.HitWindow.Close",DevComment="")
+GameplayTagList=(Tag="Event.Attack.HitWindow.Open",DevComment="")
+GameplayTagList=(Tag="Event.Stun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Melee.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Stun",DevComment="")
+GameplayTagList=(Tag="State.Combat",DevComment="")

